In [4]:
import pandas as pd

BASE = "https://raw.githubusercontent.com/Greco1899/scrape_ufc_stats/main/"

resultados = pd.read_csv(BASE + "ufc_fight_results.csv")
ufc_fight_stats = pd.read_csv(BASE + "ufc_fight_stats.csv")
ufc_fighter_stats = pd.read_csv(BASE + "ufc_fighter_tott.csv")
ufc_fighter_details = pd.read_csv(BASE + "ufc_fighter_details.csv")
ufc_event_details = pd.read_csv(BASE + "ufc_event_details.csv")

resultados.to_csv("../dados/brutos/ufc_fight_results.csv", index=False)
ufc_fight_stats.to_csv("../dados/brutos/ufc_fight_stats.csv", index=False)
ufc_fighter_stats.to_csv("../dados/brutos/ufc_fighter_stats.csv", index=False)
ufc_fighter_details.to_csv("../dados/brutos/ufc_fighter_details.csv", index=False)
ufc_event_details.to_csv("../dados/brutos/ufc_event_details.csv", index=False)

df = pd.read_csv("../dados/brutos/ufc_fight_results.csv")

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8936 entries, 0 to 8935
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EVENT        8936 non-null   str
 1   BOUT         8936 non-null   str
 2   OUTCOME      8936 non-null   str
 3   WEIGHTCLASS  8936 non-null   str
 4   METHOD       8936 non-null   str
 5   ROUND        8936 non-null   int64
 6   TIME         8936 non-null   str
 7   TIME FORMAT  8936 non-null   str
 8   REFEREE      8910 non-null   str
 9   DETAILS      8858 non-null   str
 10  URL          8936 non-null   str
dtypes: int64(1), str(10)
memory usage: 768.1 KB

In [8]:
df.describe()

             ROUND
count  8936.000000
mean      2.350940
std       1.018654
min       1.000000
25%       1.000000
50%       3.000000
75%       3.000000
max       5.000000

In [ ]:
print("Colunas:", df.columns.tolist())

Colunas: ['EVENT', 'BOUT', 'OUTCOME', 'WEIGHTCLASS', 'METHOD', 'ROUND', 'TIME', 'TIME FORMAT', 'REFEREE', 'DETAILS', 'URL']

In [10]:
df.dtypes

EVENT            str
BOUT             str
OUTCOME          str
WEIGHTCLASS      str
METHOD           str
ROUND          int64
TIME             str
TIME FORMAT      str
REFEREE          str
DETAILS          str
URL              str
dtype: object

In [11]:
df['EVENT']

0       UFC Fight Night: Rosas Jr. vs. Barcelos
1       UFC Fight Night: Rosas Jr. vs. Barcelos
2       UFC Fight Night: Rosas Jr. vs. Barcelos
3       UFC Fight Night: Rosas Jr. vs. Barcelos
4       UFC Fight Night: Rosas Jr. vs. Barcelos
                          ...
8931                          UFC 2: No Way Out
8932                          UFC 2: No Way Out
8933                          UFC 2: No Way Out
8934                          UFC 2: No Way Out
8935                          UFC 2: No Way Out
Name: EVENT, Length: 8936, dtype: str

In [ ]:
print("Tempo mínimo : ", df['TIME'].min())
print("Tempo máximo : ", df['TIME'].max())

Tempo mínimo :  0:05
Tempo máximo :  9:56

In [17]:
df.sort_values(by='TIME', ascending=True).head(10)

,EVENT,BOUT,OUTCOME,WEIGHTCLASS,METHOD,ROUND,TIME,TIME FORMAT,REFEREE,DETAILS,URL
3735,UFC 239: Jones vs. Santos,Jorge Masvidal vs. Ben Askren,W/L,Welterweight Bout,KO/TKO,1,0:05,3 Rnd (5-5-5),Jason Herzog,Flying Knee Head,http://ufcstats.com/fight-details/70af72a72b31...
8413,UFC Fight Night 3,Duane Ludwig vs. Jonathan Goulet,W/L,Welterweight Bout,KO/TKO,1,0:06,3 Rnd (5-5-5),Mario Yamasaki,Punch to Head At Distance,http://ufcstats.com/fight-details/392089df68b1...
7132,UFC 140: Jones vs Machida,Mark Hominick vs. Chan Sung Jung,L/W,Featherweight Bout,KO/TKO,1,0:07,3 Rnd (5-5-5),Herb Dean,Punch to Head At Distance,http://ufcstats.com/fight-details/8abe79e6d300...
4779,UFC Fight Night: Gustafsson vs. Teixeira,Marcin Held vs. Damir Hadzovic,L/W,Lightweight Bout,KO/TKO,3,0:07,3 Rnd (5-5-5),Bobby Rehman,Knee to Head At Distance,http://ufcstats.com/fight-details/b166f1582946...
6914,UFC 149: Faber vs Barao,Anthony Perosh vs. Ryan Jimmo,L/W,Light Heavyweight Bout,KO/TKO,1,0:07,3 Rnd (5-5-5),Josh Rosenthal,Punch to Head At Distance,http://ufcstats.com/fight-details/ec5e9ce2be2e...
2796,UFC 263: Adesanya vs. Vettori 2,Matt Frevola vs. Terrance McKinney,L/W,Lightweight Bout,KO/TKO,1,0:07,3 Rnd (5-5-5),Jason Herzog,Punch to Head At Distance,http://ufcstats.com/fight-details/d4ad90ac5842...
7755,UFC 102: Couture vs Nogueira,Todd Duffee vs. Tim Hague,W/L,Heavyweight Bout,KO/TKO,1,0:07,3 Rnd (5-5-5),Mario Yamasaki,Punch to Head At Distance,http://ufcstats.com/fight-details/fa0d393a452c...
3178,UFC Fight Night: Waterson vs. Hill,Billy Quarantillo vs. Kyle Nelson,W/L,Featherweight Bout,KO/TKO,3,0:07,3 Rnd (5-5-5),Marc Goddard,Punch to Head At Distance,http://ufcstats.com/fight-details/c58aaabf2c56...
5859,UFC on FOX: Gustafsson vs Johnson,Andy Ogle vs. Makwan Amirkhani,L/W,Featherweight Bout,KO/TKO,1,0:08,3 Rnd (5-5-5),Kevin Sataki,Punches to Head At Distance,http://ufcstats.com/fight-details/9c1d4f57a997...
8863,UFC 8: David vs Goliath,Don Frye vs. Thomas Ramirez,W/L,Open Weight Bout,KO/TKO,1,0:08,1 Rnd (10),John McCarthy,Punch to Head At Distance,http://ufcstats.com/fight-details/3cf658315307...

In [ ]:
df[['BOUT','OUTCOME']]

                                         BOUT OUTCOME
0           Raul Rosas Jr. vs. Raoni Barcelos     W/L
1                Norma Dumont vs. Ailin Perez     L/W
2          Luis Hernandez vs. Sedriques Dumas     W/L
3     Mahammadali Osmanli vs. Ilimbek Akylbek     L/W
4                Melissa Amaya vs. Tina Black     L/W
...                                       ...     ...
8931        Orlando Wiet vs. Robert Lucarelli     W/L
8932        Frank Hamaker vs. Thaddeus Luster     W/L
8933          Johnny Rhodes vs. David Levicki     W/L
8934             Patrick Smith vs. Ray Wizard     W/L
8935          Scott Morris vs. Sean Daugherty     W/L

[8936 rows x 2 columns]

In [31]:
df[(df['METHOD'] == "KO/TKO ") & (df['ROUND'] == 1)].head(10)

,EVENT,BOUT,OUTCOME,WEIGHTCLASS,METHOD,ROUND,TIME,TIME FORMAT,REFEREE,DETAILS,URL
8,UFC Fight Night: Rosas Jr. vs. Barcelos,Elves Brener vs. Josiah Harrell,W/L,Lightweight Bout,KO/TKO,1,4:14,3 Rnd (5-5-5),Herb Dean,Punch to Head At Distance,http://ufcstats.com/fight-details/15d95453729f...
11,UFC Fight Night: Rosas Jr. vs. Barcelos,Vanessa Demopoulos vs. Yazmin Jauregui,L/W,Women's Strawweight Bout,KO/TKO,1,1:02,3 Rnd (5-5-5),Blake Grice,Punches to Head From Side Control,http://ufcstats.com/fight-details/f34e58d365bb...
13,UFC 331: Van vs. Pantoja 2,Arman Tsarukyan vs. Mauricio Ruffy,W/L,Lightweight Bout,KO/TKO,1,4:56,5 Rnd (5-5-5-5-5),Jason Herzog,Elbow to Head In Clinch,http://ufcstats.com/fight-details/fe612d20eec7...
14,UFC 331: Van vs. Pantoja 2,Patricio Pitbull vs. Dooho Choi,W/L,Featherweight Bout,KO/TKO,1,3:28,3 Rnd (5-5-5),Mike Beltran,Punches to Head From Half Guard,http://ufcstats.com/fight-details/f7810c98786c...
15,UFC 331: Van vs. Pantoja 2,Gable Steveson vs. Sean Sharaf,L/W,Heavyweight Bout,KO/TKO,1,0:12,3 Rnd (5-5-5),Frank Trigg,Punch to Head At Distance,http://ufcstats.com/fight-details/023ce4fa7b7b...
20,UFC 331: Van vs. Pantoja 2,Ryan Gandra vs. Ozzy Diaz,W/L,Middleweight Bout,KO/TKO,1,2:04,3 Rnd (5-5-5),Jonathan Romero,Punch to Head At Distance,http://ufcstats.com/fight-details/51789f77811b...
23,UFC 331: Van vs. Pantoja 2,Giga Chikadze vs. Joanderson Brito,L/W,Featherweight Bout,KO/TKO,1,1:57,3 Rnd (5-5-5),Frank Trigg,Punches to Head From Guard,http://ufcstats.com/fight-details/2e35163040eb...
32,Noche UFC: Silva vs. Delgado,Yousri Belgaroui vs. Djorden Santos,W/L,Middleweight Bout,KO/TKO,1,4:25,3 Rnd (5-5-5),Brad Frank,Punch to Head At Distance,http://ufcstats.com/fight-details/9a0e77ecd1b7...
35,Noche UFC: Silva vs. Delgado,Sean King III vs. Jessie Rosas,W/L,Featherweight Bout,KO/TKO,1,0:36,3 Rnd (10-5-5),Brad Frank,Slam to On Ground,http://ufcstats.com/fight-details/5a91827fe8c1...
37,UFC Fight Night: Hooker vs. Parnasse,Dan Hooker vs. Salahdine Parnasse,L/W,Lightweight Bout,KO/TKO,1,2:35,5 Rnd (5-5-5-5-5),Marc Goddard,Punch to Head At Distance,http://ufcstats.com/fight-details/bba8c0ab999b...

TypeError: Cannot perform reduction 'mean' with string dtype